version: '3.8'

services:
  banco:
    image: python:3.9-slim
    container_name: reto_banco
    ports:
      - "8081:5000"
    volumes:
      - ./banco:/app
    working_dir: /app
    env_file:
      - ./env/banco.env
    command: sh -c "pip install flask && python app.py"
    restart: always

  dragonball:
    image: python:3.9-slim
    container_name: reto_dbz
    ports:
      - "8082:5000"
    volumes:
      - ./dragonball:/app
    working_dir: /app
    env_file:
      - ./env/dbz.env
    command: sh -c "pip install flask && python app.py"
    restart: always

  ftp:
    image: delfer/alpine-ftp-server
    container_name: reto_ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=${FTP_USERS_VAR}
    restart: always

  samba:
    image: dperson/samba
    container_name: reto_smb
    ports:
      - "139:139"
      - "445:445"
    command: ["-u", "Admin;${SMB_PASS_1}", "-u", "usuario;${SMB_PASS_2}", "-s", "Public;/share;yes;no;no;Admin,usuario"]
    volumes:
      - /tmp:/share
    restart: always